language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - sys-img-armeabi-v7a-android-22
  - extra-android-m2repository
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
after_success:
- sh set_tags.sh
script:
- bash ./gradlew assembleDebug
deploy:
  provider: releases
  api_key:
    secure: GS3r9/lvZIz5D5eEXS1xu1OipccnWqMi58km3VJCw9v4gbv0kj/xTskQed6kCxtsUjTfM/U370cr1I3Zqc050Vz7LjfwvcdDC9dyVZd9iVeKhnQYZzgYVFj9Uw4XeQbGEZJI8SpYxdbA1UgH6eSHIrdgjMe7CNe1efKVpjEp2Hey+6MCtjg5E4s2fyYEHIf8sMI07ZyBQCi86WECPbq500jyvABsmDgpJTH1xihtn4uFYtUJqRnKffMATMfPOVOBxr97JKPq6i20/wu9aUckJ/Lu3VCDqoi0Pet5XC1TkJOjdpPsuTQZcIxHED4KL21qq4vJdITWtEZ36zE4nLnJBLW78SamutYmmqK/0OezGnP4ogFjB//jQgZltV/bVmNXP5oIFquqwQHkWKab7IcqVUSXA1A1ciJR0FWCJWBUjWZ/cH97p3Gh7YKF9RDU/JkNVmGteb2RSWQNzepXIcWIGdOxL2oRVx8dkw/c+qT/DHY/C6pNegBbSrKQJM4EbUBJmp/hdHZVv2EN6BgvempOgB/zv710ikOkMZKZ4OUcetFb2Smw0aEE5tWQ8x+a7dR50rYHCLjs4BNB71H0fKAVVHd6aAbVUPnSIjSWkqks0te+kAFqoLdWTdhf7HohGriXpPrfnulbNSEWgg9L3ccBYvHXy//oE6QEztbbNJH6eTg=
  file: "./app/build/outputs/apk/app*.apk"
  on:
    repo: namanmehta1997/pdm
    branch: newStable
